# Join Leeractiviteitspecificatie → specialisatieVan → Leeractiviteitspecificatie2
SELECT DISTINCT ?Leeractiviteitspecificatie_url ?Leeractiviteitspecificatie2_url WHERE {
  ?Leeractiviteitspecificatie_url a <http://data.europa.eu/snb/model/elm/LearningActivitySpecification> .
  ?Leeractiviteitspecificatie2_url a <http://data.europa.eu/snb/model/elm/LearningActivitySpecification> .
  ?Leeractiviteitspecificatie_url <http://data.europa.eu/snb/model/elm/specialisationOf> ?Leeractiviteitspecificatie2_url .
}
