# Join Doel → type → Doelgroep
SELECT DISTINCT ?Doel_url ?Doelgroep_url WHERE {
  ?Doel_url a <http://data.europa.eu/snb/model/elm/LearningAchievement> .
  ?Doelgroep_url a <http://www.w3.org/2004/02/skos/core#Concept> .
  ?Doel_url <http://purl.org/dc/terms/type> ?Doelgroep_url .
}
